# Generated by Django 3.2.4 on 2021-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
