# Generated by Django 3.2.4 on 2021-06-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210611_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cateogry',
            new_name='category',
        ),
    ]
