# Generated by Django 3.2.4 on 2021-06-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210611_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecampaign',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
